version: "2"
services:
  app:
    container_name: userlogin
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo2
    image: mongo
    ports:
      - "27017:27017"